name: Sync Main to Develop

on:
  workflow_run:
    workflows: ["Deploy to Play Store"]
    types:
      - completed

permissions:
  contents: write

jobs:
  sync_develop:
    name: Sync Main -> Develop
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Main to Develop
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Checkout develop branch
          git checkout develop
          git pull origin develop --rebase
          
          # Merge main into develop
          git merge origin/main --no-edit -m "[CHORE] Sync main to develop [skip ci]"
          
          # Push changes
          git push origin develop
